global:
  message: "Welcome  to global microservices!"
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure: health, info, refresh
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/