spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: false